// ============================================================================
// appointments — single-file build for the Supabase dashboard editor.
//
// GENERATED. Do not edit this file: change supabase/functions/appointments/index.ts
// or supabase/functions/_shared/utils.ts, then run
//   node supabase/dashboard-paste/build.mjs
// ============================================================================

// Shared helpers for the n8n-facing Edge Functions (PRD §6).
import { createClient, type SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2.49.1'

export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-api-key',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

export function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

export function serviceClient(): SupabaseClient {
  return createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    { auth: { persistSession: false } },
  )
}

export interface Tenant {
  doctor_id: string
  clinic_name: string | null
  full_name: string
}

/**
 * Resolves which doctor a request belongs to.
 *
 * The service role bypasses RLS, so tenancy here is entirely the caller's key:
 * `x-api-key` is matched against the unique `doctors.n8n_api_key`, and the
 * doctor it belongs to is the only tenant the request may touch. There is
 * deliberately no environment-variable fallback — a single shared key could not
 * say which practice a WhatsApp booking was for.
 */
export async function resolveTenant(
  request: Request,
  client: SupabaseClient,
): Promise<{ tenant: Tenant } | { error: Response }> {
  const provided = request.headers.get('x-api-key')?.trim()
  if (!provided) return { error: json({ error: 'Missing x-api-key header' }, 401) }

  const { data, error } = await client
    .from('doctors')
    .select('id, clinic_name, full_name')
    .eq('n8n_api_key', provided)
    .maybeSingle()

  if (error) return { error: json({ error: error.message }, 500) }
  if (!data) return { error: json({ error: 'Invalid API key' }, 401) }

  return {
    tenant: { doctor_id: data.id, clinic_name: data.clinic_name, full_name: data.full_name },
  }
}

/** Path segments after the function name, e.g. /appointments/<id>/cancel -> [id, 'cancel']. */
export function pathSegments(request: Request, functionName: string): string[] {
  const { pathname } = new URL(request.url)
  const parts = pathname.split('/').filter(Boolean)
  const index = parts.indexOf(functionName)
  return index === -1 ? [] : parts.slice(index + 1)
}

/** Phone numbers arrive in mixed shapes; store one canonical form per patient. */
export function normalizePhone(raw: string): string {
  const trimmed = raw.trim()
  const digits = trimmed.replace(/[^\d+]/g, '')
  if (digits.startsWith('+')) return `+${digits.slice(1).replace(/\D/g, '')}`
  return digits
}

//////////////////////////////////////////////////////////////////////////////

// POST /appointments               -> create a booking from the WhatsApp agent
// POST /appointments/:id/cancel    -> patient cancelled via WhatsApp
//
// Both require the header `x-api-key: <the doctor's key>` (PRD §6). That key
// identifies the tenant: everything read or written below is scoped to the
// doctor it belongs to, because the service role bypasses RLS.

interface BookingPayload {
  booking_id?: string
  patient_name?: string
  phone?: string
  age?: number | null
  gender?: string | null
  scheduled_at?: string
  reason?: string | null
  meeting_link?: string | null
}

Deno.serve(async (request) => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  if (request.method !== 'POST') return json({ error: 'Method not allowed' }, 405)

  const client = serviceClient()

  const resolved = await resolveTenant(request, client)
  if ('error' in resolved) return resolved.error
  const { doctor_id: doctorId } = resolved.tenant

  const segments = pathSegments(request, 'appointments')

  /* ------------------------------------------- POST /appointments/:id/cancel */
  if (segments.length === 2 && segments[1] === 'cancel') {
    const appointmentId = segments[0]

    const { data, error } = await client
      .from('appointments')
      .update({ status: 'cancelled' })
      .eq('id', appointmentId)
      // Never let one practice's key cancel another practice's appointment.
      .eq('doctor_id', doctorId)
      .select('id, status')
      .maybeSingle()

    if (error) return json({ error: error.message }, 400)
    if (!data) return json({ error: 'Appointment not found' }, 404)
    return json({ appointment_id: data.id, status: data.status })
  }

  if (segments.length > 0) return json({ error: 'Unknown route' }, 404)

  /* -------------------------------------------------- POST /appointments */
  let payload: BookingPayload
  try {
    payload = await request.json()
  } catch {
    return json({ error: 'Body must be valid JSON' }, 400)
  }

  const name = payload.patient_name?.trim()
  const phone = payload.phone ? normalizePhone(payload.phone) : ''
  const scheduledAt = payload.scheduled_at?.trim()

  const missing = [
    !name && 'patient_name',
    !phone && 'phone',
    !scheduledAt && 'scheduled_at',
  ].filter(Boolean)

  if (missing.length > 0) {
    return json({ error: `Missing required field(s): ${missing.join(', ')}` }, 400)
  }

  if (Number.isNaN(Date.parse(scheduledAt!))) {
    return json({ error: 'scheduled_at must be an ISO 8601 timestamp' }, 400)
  }

  // Idempotency: the agent may retry a webhook it already delivered.
  if (payload.booking_id) {
    const { data: existing } = await client
      .from('appointments')
      .select('id')
      .eq('n8n_booking_id', payload.booking_id)
      .eq('doctor_id', doctorId)
      .maybeSingle()

    if (existing) return json({ appointment_id: existing.id, deduplicated: true })
  }

  /* ------------------- upsert the patient by phone, within this practice ---- */
  const { data: found } = await client
    .from('patients')
    .select('id, age, gender')
    .eq('doctor_id', doctorId)
    .eq('phone', phone)
    .maybeSingle()

  let patientId = found?.id ?? null

  if (patientId) {
    // Only fill in blanks — never overwrite details the doctor curated.
    const patch: Record<string, unknown> = {}
    if (found!.age == null && payload.age != null) patch.age = payload.age
    if (!found!.gender && payload.gender) patch.gender = payload.gender
    if (Object.keys(patch).length > 0) {
      await client.from('patients').update(patch).eq('id', patientId)
    }
  } else {
    const { data: created, error: patientError } = await client
      .from('patients')
      .insert({
        doctor_id: doctorId,
        full_name: name,
        phone,
        age: payload.age ?? null,
        gender: payload.gender ?? null,
        source: 'whatsapp',
      })
      .select('id')
      .single()

    if (patientError) return json({ error: patientError.message }, 400)
    patientId = created.id
  }

  /* ---------------------------------------------- create the appointment */
  const { data: appointment, error: appointmentError } = await client
    .from('appointments')
    .insert({
      doctor_id: doctorId,
      patient_id: patientId,
      scheduled_at: new Date(scheduledAt!).toISOString(),
      reason: payload.reason ?? null,
      meeting_link: payload.meeting_link ?? null,
      n8n_booking_id: payload.booking_id ?? null,
      status: 'booked',
    })
    .select('id')
    .single()

  if (appointmentError) return json({ error: appointmentError.message }, 400)

  return json({ appointment_id: appointment.id, patient_id: patientId, doctor_id: doctorId }, 201)
})
