// Generates single-file versions of the Edge Functions for pasting into the
// Supabase dashboard (Edge Functions -> Deploy a new function -> Via editor),
// which has no folder above the function to import `_shared/utils.ts` from.
//
// Regenerate after touching either function or the shared helpers:
//   node supabase/dashboard-paste/build.mjs
//
// The CLI route (`npx supabase functions deploy`) does not need any of this —
// it uploads supabase/functions/ as-is. These files exist only so the functions
// can be deployed without a terminal.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const functionsDir = join(here, '..', 'functions')

const HEADER = (name) => `// ============================================================================
// ${name} — single-file build for the Supabase dashboard editor.
//
// GENERATED. Do not edit this file: change supabase/functions/${name}/index.ts
// or supabase/functions/_shared/utils.ts, then run
//   node supabase/dashboard-paste/build.mjs
// ============================================================================

`

const shared = readFileSync(join(functionsDir, '_shared', 'utils.ts'), 'utf8').trim()

for (const name of ['appointments', 'prescription-delivery-callback']) {
  const source = readFileSync(join(functionsDir, name, 'index.ts'), 'utf8')

  // Drop the import of the shared helpers — they are inlined right above.
  const body = source
    .replace(/import\s*\{[^}]*\}\s*from\s*'\.\.\/_shared\/utils\.ts'\n/, '')
    .trim()

  const out = `${HEADER(name)}${shared}\n\n${'/'.repeat(78)}\n\n${body}\n`
  writeFileSync(join(here, `${name}.ts`), out)
  console.log(`wrote ${name}.ts (${out.split('\n').length} lines)`)
}
