// ============================================================================
// prescription-delivery-callback — single-file build for the Supabase dashboard editor.
//
// GENERATED. Do not edit this file: change supabase/functions/prescription-delivery-callback/index.ts
// or supabase/functions/_shared/utils.ts, then run
//   node supabase/dashboard-paste/build.mjs
// ============================================================================

// Shared helpers for the n8n-facing Edge Functions (PRD §6).
import { createClient, type SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2.49.1'

export const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-api-key',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

export function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

export function serviceClient(): SupabaseClient {
  return createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    { auth: { persistSession: false } },
  )
}

export interface Tenant {
  doctor_id: string
  clinic_name: string | null
  full_name: string
}

/**
 * Resolves which doctor a request belongs to.
 *
 * The service role bypasses RLS, so tenancy here is entirely the caller's key:
 * `x-api-key` is matched against the unique `doctors.n8n_api_key`, and the
 * doctor it belongs to is the only tenant the request may touch. There is
 * deliberately no environment-variable fallback — a single shared key could not
 * say which practice a WhatsApp booking was for.
 */
export async function resolveTenant(
  request: Request,
  client: SupabaseClient,
): Promise<{ tenant: Tenant } | { error: Response }> {
  const provided = request.headers.get('x-api-key')?.trim()
  if (!provided) return { error: json({ error: 'Missing x-api-key header' }, 401) }

  const { data, error } = await client
    .from('doctors')
    .select('id, clinic_name, full_name')
    .eq('n8n_api_key', provided)
    .maybeSingle()

  if (error) return { error: json({ error: error.message }, 500) }
  if (!data) return { error: json({ error: 'Invalid API key' }, 401) }

  return {
    tenant: { doctor_id: data.id, clinic_name: data.clinic_name, full_name: data.full_name },
  }
}

/** Path segments after the function name, e.g. /appointments/<id>/cancel -> [id, 'cancel']. */
export function pathSegments(request: Request, functionName: string): string[] {
  const { pathname } = new URL(request.url)
  const parts = pathname.split('/').filter(Boolean)
  const index = parts.indexOf(functionName)
  return index === -1 ? [] : parts.slice(index + 1)
}

/** Phone numbers arrive in mixed shapes; store one canonical form per patient. */
export function normalizePhone(raw: string): string {
  const trimmed = raw.trim()
  const digits = trimmed.replace(/[^\d+]/g, '')
  if (digits.startsWith('+')) return `+${digits.slice(1).replace(/\D/g, '')}`
  return digits
}

//////////////////////////////////////////////////////////////////////////////

// POST /prescription-delivery-callback
// n8n reports whether the WhatsApp send succeeded (PRD §6).
// Body: { appointment_id: string, status: "sent" | "failed" }

Deno.serve(async (request) => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  if (request.method !== 'POST') return json({ error: 'Method not allowed' }, 405)

  const client = serviceClient()

  const resolved = await resolveTenant(request, client)
  if ('error' in resolved) return resolved.error
  const { doctor_id: doctorId } = resolved.tenant

  let payload: { appointment_id?: string; status?: string }
  try {
    payload = await request.json()
  } catch {
    return json({ error: 'Body must be valid JSON' }, 400)
  }

  const { appointment_id: appointmentId, status } = payload

  if (!appointmentId) return json({ error: 'Missing appointment_id' }, 400)
  if (status !== 'sent' && status !== 'failed') {
    return json({ error: 'status must be "sent" or "failed"' }, 400)
  }

  const { data, error } = await client
    .from('consultations')
    .update({ whatsapp_delivery_status: status })
    .eq('appointment_id', appointmentId)
    // A key only reports delivery for its own practice's consultations.
    .eq('doctor_id', doctorId)
    .select('id, whatsapp_delivery_status')
    .maybeSingle()

  if (error) return json({ error: error.message }, 400)
  if (!data) return json({ error: 'No consultation found for that appointment' }, 404)

  return json({ consultation_id: data.id, whatsapp_delivery_status: data.whatsapp_delivery_status })
})
